/**
 * Siigo API
 * Siigo Api v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GenericPageListModel model module.
 * @module model/GenericPageListModel
 * @version v1
 */
class GenericPageListModel {
    /**
     * Constructs a new <code>GenericPageListModel</code>.
     * @alias module:model/GenericPageListModel
     */
    constructor() { 
        
        GenericPageListModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GenericPageListModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GenericPageListModel} obj Optional instance to populate.
     * @return {module:model/GenericPageListModel} The populated <code>GenericPageListModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GenericPageListModel();

            if (data.hasOwnProperty('page')) {
                obj['page'] = ApiClient.convertToType(data['page'], 'Number');
            }
            if (data.hasOwnProperty('page_size')) {
                obj['page_size'] = ApiClient.convertToType(data['page_size'], 'Number');
            }
            if (data.hasOwnProperty('total_results')) {
                obj['total_results'] = ApiClient.convertToType(data['total_results'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Represents the current page.
 * @member {Number} page
 */
GenericPageListModel.prototype['page'] = undefined;

/**
 * Represents the number of results per page.
 * @member {Number} page_size
 */
GenericPageListModel.prototype['page_size'] = undefined;

/**
 * Respresents the total count of the results.
 * @member {Number} total_results
 */
GenericPageListModel.prototype['total_results'] = undefined;






export default GenericPageListModel;

